import { VerticalAlign } from '../../dataset/enum/VerticalAlign';
import { TdBorder, TdSlash } from '../../dataset/enum/table/Table';
import { IElement, IElementPosition } from '../Element';
import { IPadding } from '../Common';
import { IListStateSeed } from '../Draw';
import { IRow } from '../Row';

export interface ITd {
  conceptId?: string;
  id?: string;
  extension?: unknown;
  externalId?: string;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  colspan: number;
  rowspan: number;
  value: IElement[];
  trIndex?: number;
  tdIndex?: number;
  isLastRowTd?: boolean;
  isLastColTd?: boolean;
  isLastTd?: boolean;
  rowIndex?: number;
  colIndex?: number;
  rowList?: IRow[];
  positionList?: IElementPosition[];
  verticalAlign?: VerticalAlign;
  backgroundColor?: string;
  borderColor?: string;
  padding?: IPadding;
  borderTypes?: TdBorder[];
  slashTypes?: TdSlash[];
  mainHeight?: number;
  realHeight?: number;
  realMinHeight?: number;
  splitSyntheticLeadingZero?: boolean;
  splitListState?: IListStateSeed;
  disabled?: boolean;
  deletable?: boolean;
}
